// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpCollectorsAdminApi.Data;

#nullable disable

namespace SpCollectorsAdminApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250505105043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SpCollectorsAdminApi.CollectorEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CollectorEntry");
                });

            modelBuilder.Entity("SpCollectorsAdminApi.PlanDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aging")
                        .HasColumnType("TEXT");

                    b.Property<string>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("CBI")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollAdvance")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollDue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CollectorEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ins")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ORDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ORNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Planholder")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotaNComm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tax")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectorEntryId");

                    b.ToTable("PlanDetail");
                });

            modelBuilder.Entity("SpCollectorsAdminApi.PlanDetail", b =>
                {
                    b.HasOne("SpCollectorsAdminApi.CollectorEntry", null)
                        .WithMany("Entries")
                        .HasForeignKey("CollectorEntryId");
                });

            modelBuilder.Entity("SpCollectorsAdminApi.CollectorEntry", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
